export enum InsightType {
  SPENDING_PATTERN = 'SPENDING_PATTERN',
  BUDGET_VARIANCE = 'BUDGET_VARIANCE',
  CASH_FLOW_FORECAST = 'CASH_FLOW_FORECAST',
  ANOMALY_DETECTION = 'ANOMALY_DETECTION',
  SAVINGS_OPPORTUNITY = 'SAVINGS_OPPORTUNITY',
}

export enum InsightSeverity {
  INFO = 'INFO',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum InsightSource {
  REPORTING = 'REPORTING',
  RULE_ENGINE = 'RULE_ENGINE',
  AI_MODEL = 'AI_MODEL',
}
